version: "3.3"
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    networks:
      - moodle-network
    container_name: db_container
    restart: always    
    ports:
      - '3386:3306'   
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=Picolo321
      - MARIADB_USER=treinar
      - MARIADB_PASSWORD=Picolo321
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - type: bind
        source: app/moodle/mariadb_data
        target: app/moodle/bitnami/mariadb
  moodle:
    image: "docker.io/bitnami/moodle:3-debian-10"
    networks:
      - moodle-network
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_USERNAME=treinar
      - MOODLE_PASSWORD=Picolo321
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=treinar
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=Picolo321
    volumes:
      - type: bind
        source: app/moodle/moodle_data
        target: app/moodle/bitnami/moodle
      - type: bind
        source: app/moodle/moodledata_data
        target: app/moodle/bitnami/moodledata
    depends_on:
      - mariadb
networks:
    moodle-network:
       external: true
volumes:
    mariadb_data:
        external: true
    moodle_data:
        external: true
    moodledata_data:
        external: true
# need create network docker network create moodle-network
# need create volume docker volume create --name mariadb_data
# chmod 
